version: "3.1"

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: RulePolicy